import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { LanguageProvider } from "@/context/language/LanguageContext";
import { MultistepFormProvider } from "@/context/steps/multistepsContext";
import { Toaster } from "@/components/ui/toaster";
import { UserProvider } from "@/context/user/userContext";
import LandingImage from "Landing.png";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-[100svh] w-screen overflow-x-hidden`}
        style={{
          backgroundImage: "url(Landing.png)",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          backgroundSize: "cover",
        }}
      >
        <LanguageProvider>
          <UserProvider>
            <MultistepFormProvider initialStepIndex={2}>
              {children}
            </MultistepFormProvider>
          </UserProvider>
        </LanguageProvider>
        <Toaster />
      </body>
    </html>
  );
}
