export const Config = {
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
  IMAGE_GEN_API: process.env.IMAGE_GEN_API,
  SMS160_PROJECT_ID: process.env.SMS160_PROJECT_ID,
  SMS160_API_KEY: process.env.SMS160_API_KEY,
};
